sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/docker
    - $HOME/.gradle
    - $HOME/.m2

env:
  global:
    - TERM=dumb
    - CI_NODE_TOTAL=3
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2

before_install:
  - sudo docker/setup.sh
  - |
    docker run \
    -w /digdag \
    -v `pwd`/:/digdag \
    -v ~/.gradle:/root/.gradle \
    digdag-build \
    ./gradlew testClasses
  - ci/validate.sh

install:

script:
  - ci/run_test.sh
