sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

cache:
  directories:
    - $HOME/docker
    - $HOME/.gradle
    - $HOME/.m2

env:
  global:
    - TERM=dumb
    - CI_NODE_TOTAL=8
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=3
    - CI_NODE_INDEX=4
    - CI_NODE_INDEX=5
    - CI_NODE_INDEX=6
    - CI_NODE_INDEX=7

before_install:
  - sudo docker/setup.sh
  - |
    docker run \
    -w /digdag \
    -v `pwd`/:/digdag \
    -v ~/.gradle:/root/.gradle \
    digdag-build \
    ./gradlew testClasses
  - ci/validate.sh

install: true

script:
  - ci/run_test.sh

after_success:
  - ci/report_coverage.sh
