sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2
    - $HOME/.yarn-cache

env:
  global:
    - TERM=dumb
    - CI_NODE_TOTAL=8
    - BUILD_IMAGE=digdag/digdag-build:20161206T031336-352701a8b59dfe2ee19dff0f7af7b487b7eb017a
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=3
    - CI_NODE_INDEX=4
    - CI_NODE_INDEX=5
    - CI_NODE_INDEX=6
    - CI_NODE_INDEX=7

before_install:
  - |
    docker run \
    -w /digdag \
    -v `pwd`/:/digdag \
    -v $HOME/.gradle:/root/.gradle \
    $BUILD_IMAGE \
    ./gradlew testClasses
  - ci/validate.sh
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install: true

before_cache:
  - sudo chown `id -u`:`id -g` -R $HOME/.gradle $HOME/.m2  # make them cachable

script:
  - ci/run_test.sh

after_success:
  - ci/travis_report_coverage.sh
