sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2

env:
  global:
    - TERM=dumb
    - CI_NODE_TOTAL=8
    - BUILD_IMAGE=digdag/digdag-build:20161206T015538-61cc5157a311817367a680063902ac5333def6bf
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=3
    - CI_NODE_INDEX=4
    - CI_NODE_INDEX=5
    - CI_NODE_INDEX=6
    - CI_NODE_INDEX=7

before_install:
  - |
    docker run \
    -w /digdag \
    -v `pwd`/:/digdag \
    -v $HOME/.gradle:/root/.gradle \
    $BUILD_IMAGE \
    ./gradlew testClasses
  - ci/validate.sh

install: true

before_cache:
  - sudo chown `id -u`:`id -g` -R $HOME/.gradle $HOME/.m2  # make them cachable

script:
  - ci/run_test.sh

after_success:
  - ci/travis_report_coverage.sh
