sudo: required

language: java

dist: trusty

jdk:
  - oraclejdk8

services:
  - docker

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2

env:
  global:
    - TERM=dumb
    - CI_NODE_TOTAL=8
    - BUILD_IMAGE=digdag/digdag-build:20190524T161614-143f954fdad17cdbe77c88a4732ca9bbd667229e
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=3
    - CI_NODE_INDEX=4
    - CI_NODE_INDEX=5
    - CI_NODE_INDEX=6
    - CI_NODE_INDEX=7

before_install:
  - sudo service --status-all
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/redis-server stop
  - |
    docker run \
    -w /digdag \
    -v `pwd`/:/digdag \
    -v $HOME/.gradle:/root/.gradle \
    $BUILD_IMAGE \
    ./gradlew testClasses --no-daemon
  - ci/validate.sh

install: true

before_cache:
  - sudo chown `id -u`:`id -g` -R $HOME/.gradle $HOME/.m2  # make them cachable

script:
  - travis_wait 40 ci/run_test.sh

after_success:
  - ci/travis_report_coverage.sh

after_failure:
  - sudo free -m -t
  - sudo dmesg
