version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat cleanTest test --info --stacktrace --no-daemon
  # TODO: come up with a better way to list tests that we want to run on appveyor
  - gradlew.bat :digdag-test:test --tests acceptance.InitIT --info --stacktrace --no-daemon

cache:
  - C:\Users\appveyor\.gradle

environment:
  NPM: C:\Program Files (x86)\nodejs\npm.cmd
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - ps: Install-Product node '12'
  - node --version
  - npm --version

test: off

branches:
  only:
    - master
    - v0_11
