# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches:
    - master
    - v0_10
    - v0_11
  pull_request:
    branches: []
#   branches:
#   - master
#   - v0_10
#   - v0_11

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ci_node_index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run tests in Docker
      run: ci/run_test.sh
      env:
        CI_NODE_INDEX: ${{ matrix.ci_node_index }}
        CI_NODE_TOTAL: 10
        BUILD_IMAGE: digdag/digdag-build:20191203T225216-c5b7206657c98c728b183634079f0a919ee98f8c

